spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: salvatore05
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  port: 1337 # Change this, just for testing purposes

jwt:
  secret: changeme
  expiration: 24 # Hours