spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: salvatore05
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  port: 1337 # Change this, just for testing purposes

jwt:
  secret: changeme
  expiration: 24 # Hours

logging:
  level:
    org:
      hibernate:
        stat: debug
        SQL_SLOW: info
        SQL: debug
        cache: debug
        orm:
          jdbc:
            bind: trace
