
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: salvatore05
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test_blog

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  profiles:
    port: 1337 # Change this, just for testing purposes

  jwt:
    secret: testtoken
    expiration: 1 # Hours


logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
