DROP DATABASE IF EXISTS test_blog;

CREATE DATABASE test_blog;

USE test_blog;

CREATE TABLE Users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    surname VARCHAR(32) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL
);

CREATE TABLE Tags (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tagname VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE Posts (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(64) NOT NULL,
    content TEXT NOT NULL,
    CODOwner INT,
    FOREIGN KEY (CODOwner) REFERENCES Users(id)
);

CREATE TABLE Tags_Posts (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CODTag INT NOT NULL,
    CODPost INT NOT NULL,
    FOREIGN KEY (CODTag) REFERENCES Tags(id),
    FOREIGN KEY (CODPost) REFERENCES Posts(id)
);